APR-40 init checking email service
bcgov/RSBC-DataHub-API pull request #280
Opened 2024-02-26 20:51 UTC by pabdi

For the JIRA task: https://justice.gov.bc.ca/jira/browse/APR-40
Updating to spring boot 3.2.3 java 17
Adding multi attachments support
Adding postman testing for multi attachments

Still todo is adding simple authorization.
More unit tests and docs

2024-02-26 22:50 UTC, shaunmillargov commented on Java/mail-it/COMPLIANCE.yaml
Can you please remove this file. Thx

2024-02-26 22:51 UTC, shaunmillargov commented on Java/mail-it/Mail-it.postman_collection.json
Please remove this file too.

2024-02-26 22:55 UTC, shaunmillargov commented on Java/mail-it/.gitignore
This file does not exclude the 'target folder and all it's folders' This is important otherwise someone may check this folder in (we don't want that in a maven project).  If you need help with this, please let me know.

2024-02-26 23:05 UTC, shaunmillargov commented on Java/mail-it/src/mail-it/src/main/resources/application.yml
> +    host: ${JMT_SPRING_EMAIL_HOST:mailhog}
Remove the JMT_SPRING from these enviro variables please.

2024-02-26 23:05 UTC, shaunmillargov requested changes
See my comments. 
Thank you Peiman.

2024-02-26 23:16 UTC, pabdi commented on Java/mail-it/src/mail-it/src/main/java/ca/bc/gov/open/rsbc/mailit/mail/controller/MailApiController.java
> +                            new ByteArrayDataSource(emailAttachment.getFilecontents(), "application/octet-stream"));
not yet but can try

2024-02-27 20:52 UTC, shaunmillargov requested changes
Peiman. Watch committing real values to the repo.

2024-02-27 21:04 UTC, pabdi commented on Java/mail-it/src/mail-it/src/main/java/ca/bc/gov/open/rsbc/mailit/mail/controller/MailApiController.java
> +                            new ByteArrayDataSource(emailAttachment.getFilecontents(), "application/octet-stream"));
tested with real mail server and works as expected.

2024-02-27 21:05 UTC, pabdi commented on Java/mail-it/src/mail-it/src/main/resources/application.yml
> +    host: ${EMAIL_HOST:apps.smtp.gov.bc.ca}
sorry missed

2024-02-28 21:43 UTC, shaunmillargov commented on Java/mail-it/src/mail-it/src/main/java/ca/bc/gov/open/rsbc/mailit/mail/MailConfig.java
> +    @Value("${mail-auth.clientSecret}")
Could you pls rename these to mail-auth.password and mail-auth.user please? More appropriate to basic auth which uses a user and password compared to oauth which uses id's and secrets, thanks.

2024-02-28 22:15 UTC, shaunmillargov approved these changes
Thank you

2024-02-28 22:15 UTC, merged